import { StyleSheet } from 'react-native';
import { colors, radii, spacing } from '../theme';

export const screenUi = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  content: { paddingHorizontal: spacing.md, paddingBottom: spacing.md },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 4,
  },
  back: { color: colors.primary, fontSize: 16 },
  title: { fontSize: 20, fontWeight: '700', color: colors.text },
  addBtn: {
    backgroundColor: colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radii.md,
  },
  addBtnText: { color: colors.text, fontWeight: '600', fontSize: 14 },
  filterRow: { marginBottom: 6 },
  filterRowContent: { gap: 6, paddingRight: 8 },
  chip: {
    backgroundColor: colors.surfaceElevated,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  chipText: { fontSize: 13, color: colors.textMuted, fontWeight: '500' },
  chipTextActive: { color: colors.text, fontWeight: '600' },
  summaryBar: {
    flexDirection: 'row',
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    padding: 12,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: colors.border,
  },
  sumItem: { alignItems: 'center', flex: 1 },
  sumDivider: { width: 1, backgroundColor: colors.border },
  sumLabel: { fontSize: 11, color: colors.textMuted },
  sumValue: { fontSize: 15, fontWeight: '700', marginTop: 2, color: colors.text },
  hint: { fontSize: 11, color: colors.textMuted, textAlign: 'center', marginBottom: 8 },
  emptyText: { textAlign: 'center', color: colors.textMuted, marginTop: 40, lineHeight: 22 },
  tabs: { flexDirection: 'row', gap: 8, marginBottom: 10 },
  tabBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: radii.md,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
  },
  tabBtnActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  tabBtnText: { fontSize: 13, fontWeight: '600', color: colors.textMuted },
  tabBtnTextActive: { color: colors.text },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radii.md,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  searchInput: { flex: 1, marginLeft: 8, fontSize: 16, color: colors.text },
  filterLabel: { fontSize: 12, color: colors.textMuted, fontWeight: '500', marginBottom: 4 },
  countLabel: { fontSize: 11, color: colors.textMuted, textAlign: 'right', marginBottom: 8 },
  card: {
    backgroundColor: colors.surface,
    padding: 14,
    borderRadius: radii.md,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  modalOverlay: { flex: 1, backgroundColor: colors.overlay, justifyContent: 'flex-end' },
  modalSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radii.xl,
    borderTopRightRadius: radii.xl,
    maxHeight: '92%',
    padding: spacing.lg,
  },
  modalTitle: { fontSize: 20, fontWeight: '700', marginBottom: 16, color: colors.text },
  fieldLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.textMuted,
    marginBottom: 6,
    marginTop: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.md,
    padding: 12,
    fontSize: 16,
    backgroundColor: colors.surfaceElevated,
    color: colors.text,
  },
  saveBtn: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    borderRadius: radii.md,
    alignItems: 'center',
    marginTop: 12,
  },
  saveBtnText: { color: colors.text, fontSize: 16, fontWeight: '700' },
  cancelBtn: { paddingVertical: 14, alignItems: 'center' },
  cancelBtnText: { color: colors.textMuted, fontSize: 15 },
  cardTitle: { fontSize: 17, fontWeight: '800', color: colors.text },
  cardTitleSm: { fontSize: 15, fontWeight: '600', color: colors.text },
  cardMeta: { fontSize: 12, color: colors.textMuted, marginTop: 2 },
  cardBody: { fontSize: 14, color: colors.textMuted, marginTop: 6 },
  cardBodySm: { fontSize: 13, color: colors.textMuted, marginTop: 4 },
  cardComment: { fontSize: 12, color: colors.textMuted, marginTop: 6, fontStyle: 'italic' as const },
  cardLink: { fontSize: 12, color: colors.primary, marginTop: 10 },
  dangerIcon: { color: colors.loss, fontSize: 16 },
  sectionTitle: { fontSize: 14, fontWeight: '700', color: colors.text, marginBottom: 8 },
  sectionTitleLg: { fontSize: 15, fontWeight: '700', color: colors.text, marginBottom: 10 },
  dividerTop: { borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 10 },
  secondaryBtn: {
    backgroundColor: colors.surfaceElevated,
    borderRadius: radii.md,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  secondaryBtnText: { fontSize: 14, fontWeight: '600', color: colors.primary },
  primaryPill: {
    alignSelf: 'flex-start',
    backgroundColor: colors.primary,
    borderRadius: radii.full,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  primaryPillText: { color: colors.text, fontSize: 14, fontWeight: '600' },
  actionRow: { flexDirection: 'row', gap: 8 },
  actionBtn: { flex: 1, paddingVertical: 8, borderRadius: 7, alignItems: 'center' },
  actionBtnText: { color: colors.text, fontSize: 12, fontWeight: '600' },
  footerBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    padding: spacing.md,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  selectedCard: { borderWidth: 2, borderColor: colors.primary, backgroundColor: colors.primaryMuted },
  metricCard: {
    width: '48%',
    backgroundColor: colors.surfaceElevated,
    borderRadius: radii.md,
    padding: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  widgetCard: {
    width: '48%',
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
  },
  archiveCard: { backgroundColor: colors.surfaceElevated, borderColor: colors.border },
  archiveBadge: {
    backgroundColor: 'rgba(251,140,0,0.2)',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  archiveBadgeText: { fontSize: 11, color: colors.warning, fontWeight: '600' },
  calendarContainer: {
    marginTop: 8,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceElevated,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 10,
  },
  dateField: {
    flex: 1,
    borderWidth: 1,
    borderRadius: radii.sm,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: colors.surfaceElevated,
  },
  selectField: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    borderRadius: radii.sm,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 10,
  },
  optionTile: { paddingVertical: 10, paddingHorizontal: 14, borderRadius: radii.sm, borderWidth: 1, marginBottom: 6 },
  optionTileActive: { borderColor: colors.primary, backgroundColor: colors.primaryMuted },
  optionTileIdle: { borderColor: colors.border, backgroundColor: colors.surfaceElevated },
  typeTile: {
    width: '30%',
    paddingVertical: 10,
    paddingHorizontal: 6,
    borderRadius: radii.sm,
    alignItems: 'center',
    borderWidth: 1.5,
    minHeight: 60,
    justifyContent: 'center',
  },
  typeTileActive: { backgroundColor: colors.primaryMuted, borderColor: colors.primary },
  typeTileIdle: { backgroundColor: colors.surfaceElevated, borderColor: colors.border },
});
