export type AdminTabParamList = {
  AdminHome: undefined;
  Orders: undefined;
  Expenses: undefined;
  Contractors: undefined;
  AdminMore: undefined;
};

export type DriverTabParamList = {
  DriverHome: undefined;
  DriverOrders: undefined;
  FinancesHub: undefined;
  DriverMore: undefined;
};

export type RootStackParamList = {
  Login: undefined;
  Register: undefined;
  ForgotPassword: undefined;
  AdminHome: undefined;
  Contractors: undefined;
  Drivers: undefined;
  Expenses: undefined;
  Orders: undefined;
  RegistryReport: undefined;
  FinancesHub: undefined;
  AdminMore: undefined;
  DriverHome: undefined;
  DriverOrders: undefined;
  DriverFinancesHub: undefined;
  DriverMore: undefined;
  OrderCreate: { templateId?: number } | undefined;
  OrderEdit: { id: number };
  Templates: undefined;
  OrderTemplates: undefined;
  OrderDetail: { id: number };
  Finances: undefined;
  AdminFinances: undefined;
  DriverFinances: undefined;
  Earnings: undefined;
  Salary: undefined;
  ContractorDebt: { contractorId?: number } | undefined;
  Materials: undefined;
  Vehicles: undefined;
  Waybills: undefined;
  Invoices: undefined;
  Notifications: undefined;
  AdminRegistrationRequests: undefined;
  ActivityLog: undefined;
  FinanceReport: undefined;
  CompleteProfile: undefined;
  Documents: undefined;
  VehicleDocuments: { vehicleId?: number } | undefined;
  Reports: undefined;
  TripCreate: { orderId: number; openAction?: 'loading' | 'unloading' };
  TripPhotos: undefined;
  AllPhotos: undefined;
  ServerSetup: { reason?: string } | undefined;
  Backups: undefined;
  About: undefined;
};
