import type {
  Contractor,
  Driver,
  Order,
  RegistrationRequest,
  SalaryEntry,
  Transaction,
  Trip,
} from "./types"

export const DRIVERS: Driver[] = [
  {
    id: "d1",
    name: "Иван Петров",
    plate: "А412ВТ 77",
    carModel: "КАМАЗ 5490",
    phone: "+7 916 234-12-90",
    fuelCard: "OPTI •••• 4821",
    salary: 85000,
    roles: ["driver"],
  },
  {
    id: "d2",
    name: "Сергей Михайлов",
    plate: "В728КК 50",
    carModel: "MAN TGX",
    phone: "+7 925 110-44-21",
    fuelCard: "OPTI •••• 7733",
    salary: 92000,
    roles: ["driver"],
  },
  {
    id: "d3",
    name: "Алексей Соколов",
    plate: "Е305МР 99",
    carModel: "Volvo FH",
    phone: "+7 903 765-88-10",
    fuelCard: "OPTI •••• 1290",
    salary: 88000,
    roles: ["driver"],
  },
  {
    id: "d4",
    name: "Дмитрий Кузнецов",
    plate: "Н991СС 77",
    carModel: "Scania R450",
    phone: "+7 909 332-09-55",
    fuelCard: "OPTI •••• 5567",
    salary: 90000,
    roles: ["driver"],
  },
]

// The logged-in driver for the driver cabinet
export const CURRENT_DRIVER_ID = "d1"

// The admin / owner account name shown in the admin cabinet header
export const ADMIN_NAME = "Андрей Волков"
export const COMPANY_NAME = "ООО «РеестрПро»"

function iso(daysAgo: number, hour = 10, min = 0): string {
  const d = new Date()
  d.setDate(d.getDate() - daysAgo)
  d.setHours(hour, min, 0, 0)
  return d.toISOString()
}

const STATIONS = ["Лукойл АЗС №112", "Газпромнефть №48", "Роснефть №203", "ТАТНЕФТЬ №77"]

let counter = 0
function id() {
  counter += 1
  return `tx${counter}`
}

function driverOf(driverId: string) {
  const d = DRIVERS.find((x) => x.id === driverId)!
  return { driverId: d.id, driverName: d.name, carPlate: d.plate }
}

export const TRANSACTIONS: Transaction[] = [
  // ---- Today ----
  {
    id: id(),
    category: "fuel",
    amount: 9840,
    date: iso(0, 8, 12),
    ...driverOf("d1"),
    source: "opti",
    status: "matched",
    payStatus: "paid",
    station: STATIONS[0],
    liters: 168,
    payments: [],
  },
  {
    id: id(),
    category: "dps",
    amount: 5000,
    date: iso(0, 9, 40),
    comment: "Превышение скорости, ст. 12.9 ч.2",
    ...driverOf("d1"),
    source: "driver",
    status: "manual",
    payStatus: "unpaid",
    approval: "pending",
    hasReceipt: true,
    payments: [],
  },
  {
    id: id(),
    category: "wash",
    amount: 1200,
    date: iso(0, 11, 5),
    comment: "Мойка кузова + двигатель",
    ...driverOf("d1"),
    source: "driver",
    status: "manual",
    payStatus: "paid",
    approval: "approved",
    hasReceipt: true,
    payments: [],
  },
  {
    id: id(),
    category: "other",
    amount: 2400,
    date: iso(0, 12, 30),
    comment: "Платная дорога М-12",
    ...driverOf("d1"),
    source: "driver",
    status: "manual",
    payStatus: "unpaid",
    approval: "pending",
    payments: [],
  },
  {
    id: id(),
    category: "fuel",
    amount: 11200,
    date: iso(0, 7, 30),
    ...driverOf("d2"),
    source: "opti",
    status: "imported",
    payStatus: "paid",
    station: STATIONS[1],
    liters: 191,
    payments: [],
  },
  {
    id: id(),
    category: "repair",
    amount: 24500,
    date: iso(0, 14, 20),
    comment: "Замена тормозных колодок",
    ...driverOf("d3"),
    source: "driver",
    status: "manual",
    payStatus: "partial",
    approval: "pending",
    hasReceipt: true,
    payments: [
      {
        id: "p1",
        contractor: 'СТО "Грузовик-Сервис"',
        amount: 12000,
        date: iso(0, 15, 0),
        comment: "Аванс наличными",
      },
    ],
  },
  // ---- Earlier this month ----
  {
    id: id(),
    category: "fuel",
    amount: 10350,
    date: iso(2, 9, 0),
    ...driverOf("d1"),
    source: "opti",
    status: "matched",
    payStatus: "paid",
    station: STATIONS[2],
    liters: 176,
    payments: [],
  },
  {
    id: id(),
    category: "dps",
    amount: 1500,
    date: iso(3, 13, 15),
    comment: "Стоянка в неположенном месте",
    ...driverOf("d2"),
    source: "driver",
    status: "manual",
    payStatus: "paid",
    approval: "approved",
    payments: [
      {
        id: "p2",
        contractor: "ГИБДД (Госуслуги)",
        amount: 1500,
        date: iso(2, 10, 0),
        comment: "Оплачено со скидкой 50%",
      },
    ],
  },
  {
    id: id(),
    category: "wash",
    amount: 800,
    date: iso(3, 17, 45),
    comment: "Мойка кузова",
    ...driverOf("d1"),
    source: "driver",
    status: "manual",
    payStatus: "unpaid",
    approval: "rejected",
    rejectReason: "Нет фото чека, повторите загрузку",
    payments: [],
  },
  {
    id: id(),
    category: "fuel",
    amount: 9120,
    date: iso(3, 6, 50),
    ...driverOf("d4"),
    source: "opti",
    status: "duplicate",
    payStatus: "paid",
    station: STATIONS[3],
    liters: 155,
    payments: [],
  },
  {
    id: id(),
    category: "repair",
    amount: 8700,
    date: iso(5, 16, 0),
    comment: "Развал-схождение",
    ...driverOf("d1"),
    source: "driver",
    status: "manual",
    payStatus: "paid",
    approval: "approved",
    hasReceipt: true,
    payments: [
      {
        id: "p3",
        contractor: "ИП Морозов А.В.",
        amount: 8700,
        date: iso(5, 17, 0),
      },
    ],
  },
  {
    id: id(),
    category: "salary",
    amount: 85000,
    date: iso(6, 12, 0),
    comment: "Зарплата за период",
    ...driverOf("d1"),
    source: "admin",
    status: "manual",
    payStatus: "unpaid",
    payments: [],
  },
  {
    id: id(),
    category: "salary",
    amount: 92000,
    date: iso(6, 12, 0),
    comment: "Зарплата за период",
    ...driverOf("d2"),
    source: "admin",
    status: "manual",
    payStatus: "unpaid",
    payments: [],
  },
  {
    id: id(),
    category: "other",
    amount: 3200,
    date: iso(7, 18, 30),
    comment: "Платная трасса М-12",
    ...driverOf("d3"),
    source: "driver",
    status: "manual",
    payStatus: "paid",
    approval: "approved",
    payments: [],
  },
  {
    id: id(),
    category: "fuel",
    amount: 12750,
    date: iso(8, 8, 0),
    ...driverOf("d3"),
    source: "opti",
    status: "matched",
    payStatus: "paid",
    station: STATIONS[0],
    liters: 217,
    payments: [],
  },
  {
    id: id(),
    category: "wash",
    amount: 900,
    date: iso(9, 19, 0),
    ...driverOf("d4"),
    source: "driver",
    status: "manual",
    payStatus: "paid",
    approval: "approved",
    payments: [],
  },
  {
    id: id(),
    category: "dps",
    amount: 3000,
    date: iso(10, 11, 0),
    comment: "Нарушение режима труда и отдыха",
    ...driverOf("d4"),
    source: "driver",
    status: "manual",
    payStatus: "unpaid",
    approval: "pending",
    hasReceipt: true,
    payments: [],
  },
]

export const CONTRACTORS: Contractor[] = [
  { id: "c1", name: "ООО «СтройГрад»", inn: "7701234567", phone: "+7 495 120-33-44", debt: 480000 },
  { id: "c2", name: "АО «ДорСтрой-Регион»", inn: "5025098761", phone: "+7 495 778-21-09", debt: 0 },
  { id: "c3", name: "ООО «БетонМикс»", inn: "7733456120", phone: "+7 499 340-55-12", debt: 215000 },
  { id: "c4", name: "ИП Захаров Е.С.", inn: "771845902213", phone: "+7 916 882-44-31", debt: 64000 },
]

export const ORDERS: Order[] = [
  {
    id: "o1",
    number: "№ 1042",
    contractorId: "c1",
    contractor: "ООО «СтройГрад»",
    material: "Песок",
    volume: 90,
    fromAddress: "Карьер «Северный», Мытищи",
    toAddress: "ЖК «Восход», Балашиха",
    driverRate: 320,
    companyRate: 540,
    driverId: "d1",
    driverName: "Иван Петров",
    status: "in_progress",
    date: iso(0, 7, 0),
  },
  {
    id: "o2",
    number: "№ 1041",
    contractorId: "c3",
    contractor: "ООО «БетонМикс»",
    material: "Щебень",
    volume: 60,
    fromAddress: "Карьер «Гранит», Подольск",
    toAddress: "Завод ЖБИ-7, Видное",
    driverRate: 380,
    companyRate: 610,
    driverId: "d2",
    driverName: "Сергей Михайлов",
    status: "new",
    date: iso(0, 9, 30),
  },
  {
    id: "o3",
    number: "№ 1039",
    contractorId: "c2",
    contractor: "АО «ДорСтрой-Регион»",
    material: "ПГС",
    volume: 120,
    fromAddress: "Карьер «Заречье», Люберцы",
    toAddress: "Трасса А-107, 45 км",
    driverRate: 300,
    companyRate: 500,
    driverId: "d3",
    driverName: "Алексей Соколов",
    status: "done",
    date: iso(2, 8, 0),
  },
  {
    id: "o4",
    number: "№ 1038",
    contractorId: "c1",
    contractor: "ООО «СтройГрад»",
    material: "Грунт",
    volume: 75,
    fromAddress: "Площадка снятия, Реутов",
    toAddress: "Полигон «Эко-Восток»",
    driverRate: 260,
    companyRate: 430,
    driverId: "d4",
    driverName: "Дмитрий Кузнецов",
    status: "done",
    date: iso(4, 7, 30),
  },
  {
    id: "o5",
    number: "№ 1037",
    contractorId: "c4",
    contractor: "ИП Захаров Е.С.",
    material: "Отсев",
    volume: 40,
    fromAddress: "Карьер «Гранит», Подольск",
    toAddress: "СНТ «Луговое», Домодедово",
    driverRate: 340,
    companyRate: 560,
    status: "cancelled",
    date: iso(6, 10, 0),
  },
]

export const TRIPS: Trip[] = [
  {
    id: "t1",
    orderId: "o1",
    driverId: "d1",
    driverName: "Иван Петров",
    plate: "А412ВТ 77",
    stage: "unloading",
    volume: 30,
    ttnNumber: "ТТН-009812",
    hasTtnPhoto: true,
    loadedAt: iso(0, 8, 0),
  },
  {
    id: "t2",
    orderId: "o1",
    driverId: "d1",
    driverName: "Иван Петров",
    plate: "А412ВТ 77",
    stage: "done",
    volume: 30,
    ttnNumber: "ТТН-009804",
    hasTtnPhoto: true,
    loadedAt: iso(0, 6, 10),
    unloadedAt: iso(0, 7, 40),
  },
  {
    id: "t3",
    orderId: "o3",
    driverId: "d3",
    driverName: "Алексей Соколов",
    plate: "Е305МР 99",
    stage: "done",
    volume: 40,
    ttnNumber: "ТТН-009790",
    hasTtnPhoto: true,
    loadedAt: iso(2, 8, 30),
    unloadedAt: iso(2, 10, 5),
  },
]

export const SALARY_ENTRIES: SalaryEntry[] = [
  { id: "s1", driverId: "d1", driverName: "Иван Петров", kind: "accrual", amount: 85000, date: iso(6, 12, 0), comment: "Период 1–15" },
  { id: "s2", driverId: "d1", driverName: "Иван Петров", kind: "payment", amount: 40000, date: iso(4, 14, 0), comment: "Аванс" },
  { id: "s3", driverId: "d2", driverName: "Сергей Михайлов", kind: "accrual", amount: 92000, date: iso(6, 12, 0) },
  { id: "s4", driverId: "d2", driverName: "Сергей Михайлов", kind: "payment", amount: 92000, date: iso(1, 11, 0), comment: "Полный расчёт" },
  { id: "s5", driverId: "d3", driverName: "Алексей Соколов", kind: "accrual", amount: 88000, date: iso(6, 12, 0) },
  { id: "s6", driverId: "d4", driverName: "Дмитрий Кузнецов", kind: "accrual", amount: 90000, date: iso(6, 12, 0) },
  { id: "s7", driverId: "d4", driverName: "Дмитрий Кузнецов", kind: "payment", amount: 30000, date: iso(3, 16, 0), comment: "Аванс" },
]

export const REGISTRATION_REQUESTS: RegistrationRequest[] = [
  { id: "r1", kind: "driver", name: "Олег Тарасов", phone: "+7 905 221-78-44", detail: "Р447ТТ 77 • КАМАЗ 65115", date: iso(0, 9, 0), status: "pending" },
  { id: "r2", kind: "founder", name: 'ООО «ТрансБетон»', phone: "+7 495 661-00-12", detail: "ИНН 7702991043", date: iso(1, 13, 0), status: "pending" },
  { id: "r3", kind: "driver", name: "Виктор Лебедев", phone: "+7 912 044-19-22", detail: "У902НН 50 • MAN TGS", date: iso(2, 10, 30), status: "pending" },
]

// Revenue figures for admin P&L (mock)
export const REVENUE = {
  today: 142000,
  month: 2840000,
  todayChange: 8.4,
  monthChange: -3.1,
}
